<a href="https://colab.research.google.com/github/rhdtka21/Intro-To-AI/blob/master/HW1_%EC%84%9D%EC%A0%95%EC%9A%B0_2015003209.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

v = np.array([2, 3.8, 0, 5, 1])
u = np.exp(np.array([1,3,4,7,9]))
w = np.arange(-10,4)
m = np.arange(-3, 8, 2)
n = np.arange(0, 7, 2)
s = np.arange(0, -3.1, -0.1)
t = np.linspace(0, np.pi, 50)

In [0]:
A = np.array([[1,2,3],[5,3,1],[7,7,7]])
np.zeros((5,5))

B = np.ones((5,5)) * 2

C = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        if i != j:
            C[i][j] = 5
            
d = np.array([1,2,3,2,1])
D = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        if i == j:
            D[i][j] = d[i]

F = np.empty((1, 9), dtype=int)
for i in range(5):
    item = np.array([[1,2,3,4,5,6,7,8,9]])
    F = np.append(F, item, axis=0) 
F = np.delete(F, [0, 0], axis=0).T

In [0]:
print('1. Create the following vector variables\n\n')
print('v = ', v)
print('u = ', u)
print('w = ', w)
print('m = ', m)
print('n = ', n)
print('s = ', s)
print('t = \n', t)

print('\n\n2. Create the following matrix variables.\n\n')
print('A = \n', A)
print('B = \n', B)
print('C = \n', C)
print('D = \n', D)
print('F = \n', F)


1. Create the following vector variables


v =  [2.  3.8 0.  5.  1. ]
u =  [2.71828183e+00 2.00855369e+01 5.45981500e+01 1.09663316e+03
 8.10308393e+03]
w =  [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3]
m =  [-3 -1  1  3  5  7]
n =  [0 2 4 6]
s =  [ 0.  -0.1 -0.2 -0.3 -0.4 -0.5 -0.6 -0.7 -0.8 -0.9 -1.  -1.1 -1.2 -1.3
 -1.4 -1.5 -1.6 -1.7 -1.8 -1.9 -2.  -2.1 -2.2 -2.3 -2.4 -2.5 -2.6 -2.7
 -2.8 -2.9 -3. ]
t = 
 [0.         0.06411414 0.12822827 0.19234241 0.25645654 0.32057068
 0.38468481 0.44879895 0.51291309 0.57702722 0.64114136 0.70525549
 0.76936963 0.83348377 0.8975979  0.96171204 1.02582617 1.08994031
 1.15405444 1.21816858 1.28228272 1.34639685 1.41051099 1.47462512
 1.53873926 1.60285339 1.66696753 1.73108167 1.7951958  1.85930994
 1.92342407 1.98753821 2.05165235 2.11576648 2.17988062 2.24399475
 2.30810889 2.37222302 2.43633716 2.5004513  2.56456543 2.62867957
 2.6927937  2.75690784 2.82102197 2.88513611 2.94925025 3.01336438
 3.07747852 3.14159265]


2. Create th

In [0]:
np.log10(np.sqrt(v))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([0.150515 , 0.2898918,      -inf, 0.349485 , 0.       ])

In [0]:
np.exp(u)

array([1.51542622e+01, 5.28491311e+08, 5.14843556e+23,            inf,
                  inf])

In [0]:
np.linalg.norm(w)-3

16.974984355438178

In [0]:
np.cos(t)

array([ 1.        ,  0.99794539,  0.99179001,  0.98155916,  0.96729486,
        0.94905575,  0.92691676,  0.90096887,  0.8713187 ,  0.8380881 ,
        0.80141362,  0.76144596,  0.71834935,  0.67230089,  0.6234898 ,
        0.57211666,  0.51839257,  0.46253829,  0.40478334,  0.34536505,
        0.28452759,  0.22252093,  0.1595999 ,  0.09602303,  0.03205158,
       -0.03205158, -0.09602303, -0.1595999 , -0.22252093, -0.28452759,
       -0.34536505, -0.40478334, -0.46253829, -0.51839257, -0.57211666,
       -0.6234898 , -0.67230089, -0.71834935, -0.76144596, -0.80141362,
       -0.8380881 , -0.8713187 , -0.90096887, -0.92691676, -0.94905575,
       -0.96729486, -0.98155916, -0.99179001, -0.99794539, -1.        ])

In [0]:
A = A[::-1]
A

array([[7, 7, 7],
       [5, 3, 1],
       [1, 2, 3]])

In [0]:
B[0] = np.ones((1,5))
B[2] = np.ones((1,5)) * 3
B

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [0]:
D = np.delete(D, [1, 1], axis=0)
D

array([[1., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
C2 = C[-2:, :2]
C2

array([[5., 5.],
       [5., 5.]])

In [0]:
F[:, 0] = F[:, 0][::-1]
F

array([[9, 1, 1, 1, 1],
       [8, 2, 2, 2, 2],
       [7, 3, 3, 3, 3],
       [6, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [4, 6, 6, 6, 6],
       [3, 7, 7, 7, 7],
       [2, 8, 8, 8, 8],
       [1, 9, 9, 9, 9]])